name: ubuntu-latest build/test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install clang-9
      run: |
        sudo apt update && sudo apt install -y clang-9 libc++-9-dev libc++abi-9-dev \
            && sudo apt autoremove -y --purge

    - name: build
      run: |
        mkdir build && cd build
        CC=clang-9 CXX=clang++-9 cmake -DCMAKE_BUILD_TYPE=Release ../
        cmake --build . -- -j 2 VERBOSE=1
        sync
    - name: test
      run: |
        cd build
        ./test_file
        ./main
